[package]
name = "leptos-routable-macro"
version = "0.1.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
prettyplease = "0.2.3"
deluxe = "0.5.0"
proc-macro-error2 = "2.0.1"
syn = "2.0.96"
quote = "1.0.38"
proc-macro2 = "1.0"
darling = "0.21.0"
